# Generated by Django 5.2.4 on 2025-10-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_extragallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extragallery',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
